name: Apptainer Build

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    name: Build Apptainer image
    permissions:
      contents: read
      packages: write
    steps:
      - name: Install Apptainer
        with:
          apptainer-version: '1.2.5'
        uses: maouw/apptainer-actions/setup@dev
      - name: Check out code for the container build
        uses: actions/checkout@v4
      # - name: Clear disk space
      #   uses: maouw/apptainer-actions/make-disk-space@dev
      - name: Build and push Apptainer image
        uses: maouw/apptainer-actions/build-and-push@dev
        with:
          deffile: dir/Singularity
          xtrace: 'true'
          apptainer-tmpdir: ${{ github.workspace }}/apptainer-tmp
          image-dir: ${{ github.workspace }}
