name: Singularity Build
on:
  push:
    tags:
      - release-*

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    name: Build Apptainer image
    permissions:
        contents: read
        packages: write
    steps:
      - name: Install Apptainer
        uses: maouw/github-action-apptainer-install@b8bd401
      - name: Check out code for the container build
        uses: actions/checkout@v4
      - name: Build Container
        shell: bash
        run: |
          set -eE -o pipefail
          input_def="${input_def:-Singularity}"
          output_sif="${output_sif:-container.sif}"
          echo "Building container from $input_def to $output_sif..."
          apptainer build --fix-perms --warn-unused-build-args --fakeroot container.sif Singularity
          echo "Container built."
          echo "Cleaning up..."
          apptainer cache clean --force
          tag="${tag:-latest}"
          echo "Tag is $tag."
          echo "tag=$tag" >> $GITHUB_ENV
      - name: Login and Deploy Container
        shell: bash
        run: |
          apptainer remote login -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }} oras://ghcr.io
          apptainer push container.sif oras://ghcr.io/${{ github.repository }}:${tag}
