name: Apptainer Build
on:
  push:
    branches:
      - main
      - dev
    tags:
      - 'v*.*.*'
      - 'v*.*.*-*'
      - '*@*'

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    name: Build Apptainer image
    permissions:
        contents: read
        packages: write
    steps:
      - name: Install Apptainer
        uses: maouw/apptainer-actions/setup@v1
      - name: Check out code for the container build
        uses: actions/checkout@v4
      - name: Get version
        shell: bash
        run: |
          if [[ "${GITHUB_REF_TYPE:-}" == "tag" ]]; then
            case "${GITHUB_REF_NAME:-}" in
              v?*) IMAGE_VERSION="${GITHUB_REF_NAME#v}";;
              *@?*) IMAGE_VERSION="${GITHUB_REF_NAME#*@}";;
        *) echo "Invalid tag: \"${GITHUB_REF_NAME:-}\"" >&2; exit 1;;
          esac
          echo "IMAGE_VERSION=${IMAGE_VERSION}" >> "${GITHUB_ENV}"
         fi
      - name: Build Container
        uses: maouw/apptainer-actions/build-and-push@v1
        with:
          deffile: Singularity
          image-version: ${{ env.IMAGE_VERSION }}

